// <auto-generated />
using System;
using MFO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MFO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MfoDbContext))]
    [Migration("20260208204503_FullContext")]
    partial class FullContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MFO.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MFO.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a22c6f48-1d5c-4d03-86b8-1f2f9b3a3e14"),
                            Code = "001",
                            IsActive = true,
                            Name = "Головной офис"
                        },
                        new
                        {
                            Id = new Guid("0d2d0d7d-7317-4f0e-a62a-6e7f8a3f7f3c"),
                            Code = "002",
                            IsActive = true,
                            Name = "Филиал 2"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumericCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d2c7a1f-8b9e-4c2a-9f1d-2b3c4d5e6f70"),
                            Code = "TJS",
                            IsActive = true,
                            Name = "Таджикский сомони",
                            NumericCode = "972",
                            Symbol = "TJS"
                        },
                        new
                        {
                            Id = new Guid("1c2d3e4f-5a6b-7c8d-9e0f-1a2b3c4d5e6f"),
                            Code = "RUB",
                            IsActive = true,
                            Name = "Российский рубль",
                            NumericCode = "643",
                            Symbol = "RUB"
                        },
                        new
                        {
                            Id = new Guid("7a3d2f1c-9b4e-4a1b-8d2c-6f1a9d3b2c4d"),
                            Code = "USD",
                            IsActive = true,
                            Name = "Доллар США",
                            NumericCode = "840",
                            Symbol = "USD"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-48b9-0c1d-2e3f4a5b6c7d"),
                            Code = "EUR",
                            IsActive = true,
                            Name = "Евро",
                            NumericCode = "978",
                            Symbol = "EUR"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MFO.Domain.Entities.CustomerStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CustomerStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a2f9f2b-7f9f-41c4-9f3b-0c3d24b7c2a1"),
                            Code = "ACTIVE",
                            IsActive = true,
                            Name = "Активный"
                        },
                        new
                        {
                            Id = new Guid("9d2f7a6c-221b-4e8a-8d1f-8af2d5a3a7a7"),
                            Code = "INACTIVE",
                            IsActive = false,
                            Name = "Неактивный"
                        },
                        new
                        {
                            Id = new Guid("f1a7c4a9-5f1c-4e2a-9b4d-3f2a1d6c8e7a"),
                            Code = "BLACKLISTED",
                            IsActive = false,
                            Name = "В черном списке"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.CustomerType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c6b2b1f-8a0c-4f2b-9a5b-4b1f7c2b5d3a"),
                            Code = "INDIVIDUAL",
                            IsActive = true,
                            Name = "Физическое лицо"
                        },
                        new
                        {
                            Id = new Guid("d1a9b5c3-2f4e-4b8d-8c2e-5f3a1b7c9d0e"),
                            Code = "BUSINESS",
                            IsActive = true,
                            Name = "Юридическое лицо"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.DisbursementMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("DisbursementMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a0b1c2d-3e4f-45a6-b7c8-d9e0f1a2b3c4"),
                            Code = "CASH",
                            IsActive = true,
                            Name = "Наличные"
                        },
                        new
                        {
                            Id = new Guid("c4b3a2f1-0e9d-48c7-b6a5-4f3e2d1c0b9a"),
                            Code = "CARD",
                            IsActive = true,
                            Name = "Карта"
                        },
                        new
                        {
                            Id = new Guid("f0e9d8c7-b6a5-44f3-a2b1-c0d9e8f7a6b5"),
                            Code = "BANK_TRANSFER",
                            IsActive = true,
                            Name = "Банковский перевод"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6a1f9a5-0a5b-4a4c-9d22-8a1f78e3e81f"),
                            BranchId = new Guid("a22c6f48-1d5c-4d03-86b8-1f2f9b3a3e14"),
                            FullName = "Администратор",
                            IsActive = true
                        },
                        new
                        {
                            Id = new Guid("c9c6dfd0-93b4-4d0e-86fa-3e7a4f6e5f2f"),
                            BranchId = new Guid("a22c6f48-1d5c-4d03-86b8-1f2f9b3a3e14"),
                            FullName = "Куратор",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ApprovedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuratorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("DisbursedOn")
                        .HasColumnType("date");

                    b.Property<Guid>("DisbursementMethodId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("FeesAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly?>("MaturityOn")
                        .HasColumnType("date");

                    b.Property<decimal>("OutstandingInterest")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OutstandingPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PaymentFrequencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PenaltyPolicyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PenaltyRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<decimal>("PrincipalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurposeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RepaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<int>("TermMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPayable")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CuratorId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DisbursementMethodId");

                    b.HasIndex("PaymentFrequencyId");

                    b.HasIndex("PenaltyPolicyId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurposeId");

                    b.HasIndex("RepaymentMethodId");

                    b.HasIndex("StatusId");

                    b.ToTable("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("ClosedOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("OpenedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("LoanId");

                    b.ToTable("LoanAccounts");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaxTermMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MinTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("OriginationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("PaymentFrequencyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PenaltyPolicyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PaymentFrequencyId");

                    b.HasIndex("PenaltyPolicyId");

                    b.ToTable("LoanProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c9d0e1f-2a3b-44c5-6d7e-8f9a0b1c2d3e"),
                            Code = "SHORT_TERM",
                            CurrencyId = new Guid("7a3d2f1c-9b4e-4a1b-8d2c-6f1a9d3b2c4d"),
                            InterestRate = 2.5m,
                            IsActive = true,
                            MaxAmount = 500m,
                            MaxTermMonths = 3,
                            MinAmount = 50m,
                            MinTermMonths = 1,
                            Name = "Краткосрочный кредит",
                            OriginationFee = 5m,
                            PaymentFrequencyId = new Guid("12b4c5d6-7e8f-49a0-b1c2-3d4e5f6a7b8c"),
                            PenaltyPolicyId = new Guid("5f6a7b8c-9d0e-41f2-3a4b-5c6d7e8f9a0b")
                        },
                        new
                        {
                            Id = new Guid("9d0e1f2a-3b4c-45d6-7e8f-9a0b1c2d3e4f"),
                            Code = "LONG_TERM",
                            CurrencyId = new Guid("7a3d2f1c-9b4e-4a1b-8d2c-6f1a9d3b2c4d"),
                            InterestRate = 1.5m,
                            IsActive = true,
                            MaxAmount = 2000m,
                            MaxTermMonths = 24,
                            MinAmount = 300m,
                            MinTermMonths = 6,
                            Name = "Долгосрочный кредит",
                            OriginationFee = 10m,
                            PaymentFrequencyId = new Guid("b7c8d9e0-f1a2-43b4-85c6-d7e8f9a0b1c2"),
                            PenaltyPolicyId = new Guid("6a7b8c9d-0e1f-42a3-4b5c-6d7e8f9a0b1c")
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("LoanStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b5a3f41-2f04-4eb6-a4e8-1c4f55b2a6f1"),
                            Code = "DRAFT",
                            IsClosed = false,
                            Name = "Черновик"
                        },
                        new
                        {
                            Id = new Guid("c72b1c34-2b5d-45ad-9c3c-1c8b6d9c0f2a"),
                            Code = "PENDING",
                            IsClosed = false,
                            Name = "В ожидании"
                        },
                        new
                        {
                            Id = new Guid("8b9f77f8-9f0d-4f5c-9a49-3d1dfc55f9d7"),
                            Code = "APPROVED",
                            IsClosed = false,
                            Name = "Одобрен"
                        },
                        new
                        {
                            Id = new Guid("14cf2ac0-3d2d-4f35-9b64-8d9ef0d2a343"),
                            Code = "DISBURSED",
                            IsClosed = false,
                            Name = "Выдан"
                        },
                        new
                        {
                            Id = new Guid("2eb7d12d-1a2c-4e2d-8bbf-ff18c89c41f3"),
                            Code = "ACTIVE",
                            IsClosed = false,
                            Name = "Работает"
                        },
                        new
                        {
                            Id = new Guid("f2e57b5b-f2be-4fb7-9a4e-4bb2b57c6a2a"),
                            Code = "OVERDUE",
                            IsClosed = false,
                            Name = "Просрочен"
                        },
                        new
                        {
                            Id = new Guid("b93efb6a-1249-4b5b-9a4c-5c7a3bb4d3ae"),
                            Code = "RESTRUCTURED",
                            IsClosed = false,
                            Name = "Реструктурирован"
                        },
                        new
                        {
                            Id = new Guid("6e0f0f4e-6d4b-4d18-9ed9-5d6a6f2bc71f"),
                            Code = "PROLONGED",
                            IsClosed = false,
                            Name = "Пролонгирован"
                        },
                        new
                        {
                            Id = new Guid("d2a3547d-0b6c-4c17-9f73-7d8f2f4d6a1e"),
                            Code = "CLOSED",
                            IsClosed = true,
                            Name = "Закрыт"
                        },
                        new
                        {
                            Id = new Guid("6b8949d8-1f89-4d2b-9d39-6d3b0e2d9fd2"),
                            Code = "WRITTEN_OFF",
                            IsClosed = true,
                            Name = "Списан"
                        },
                        new
                        {
                            Id = new Guid("f7c6ec3f-5b18-4fd1-9bb1-5f0c7c8d2a91"),
                            Code = "CANCELLED",
                            IsClosed = true,
                            Name = "Отменен"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("LoanAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("OccurredOn")
                        .HasColumnType("date");

                    b.Property<Guid>("TransactionTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LoanAccountId");

                    b.HasIndex("LoanId");

                    b.HasIndex("TransactionTypeId");

                    b.ToTable("LoanTransactions");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanTransactionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("LoanTransactionTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf7b7a28-0e9a-4b5d-b9b2-2f4f6a6c0e3b"),
                            Code = "DISBURSEMENT",
                            IsActive = true,
                            Name = "Выдача кредита"
                        },
                        new
                        {
                            Id = new Guid("8b72e8f5-51a6-4c72-95c2-4ad5f6a7d8f1"),
                            Code = "REPAYMENT",
                            IsActive = true,
                            Name = "Погашение кредита"
                        },
                        new
                        {
                            Id = new Guid("7e2a4d8d-49f1-4f0b-9c2d-7b1f8f6a1e2c"),
                            Code = "ACCOUNT_TOPUP",
                            IsActive = true,
                            Name = "Пополнение счета"
                        },
                        new
                        {
                            Id = new Guid("a1c4d7e9-3b5f-4b2c-9a3e-2d6f8b1c7e0a"),
                            Code = "RESTRUCTURE",
                            IsActive = true,
                            Name = "Реструктуризация"
                        },
                        new
                        {
                            Id = new Guid("b2d5e8f1-4c6a-4d3b-8e1f-3c7a9d2e6f0b"),
                            Code = "PROLONGATION",
                            IsActive = true,
                            Name = "Пролонгация"
                        },
                        new
                        {
                            Id = new Guid("c3e6f9a2-5d7b-4e4c-9f2a-4d8b0e3f7a1c"),
                            Code = "PENALTY",
                            IsActive = true,
                            Name = "Штраф"
                        },
                        new
                        {
                            Id = new Guid("d4f7a0b3-6e8c-4f5d-8a3b-5e9c1f4a8b2d"),
                            Code = "WRITE_OFF",
                            IsActive = true,
                            Name = "Списание"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.PaymentFrequency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("PaymentFrequencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("12b4c5d6-7e8f-49a0-b1c2-3d4e5f6a7b8c"),
                            Code = "WEEKLY",
                            IntervalDays = 7,
                            IsActive = true,
                            Name = "Еженедельно"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-47a8-9b0c-1d2e3f4a5b6c"),
                            Code = "BIWEEKLY",
                            IntervalDays = 14,
                            IsActive = true,
                            Name = "Раз в две недели"
                        },
                        new
                        {
                            Id = new Guid("b7c8d9e0-f1a2-43b4-85c6-d7e8f9a0b1c2"),
                            Code = "MONTHLY",
                            IntervalDays = 30,
                            IsActive = true,
                            Name = "Ежемесячно"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.PenaltyPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("FixedFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PenaltyRate")
                        .HasPrecision(7, 4)
                        .HasColumnType("numeric(7,4)");

                    b.HasKey("Id");

                    b.ToTable("PenaltyPolicies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5f6a7b8c-9d0e-41f2-3a4b-5c6d7e8f9a0b"),
                            Code = "STANDARD",
                            FixedFee = 0m,
                            IsActive = true,
                            Name = "Стандартный",
                            PenaltyRate = 0.5m
                        },
                        new
                        {
                            Id = new Guid("6a7b8c9d-0e1f-42a3-4b5c-6d7e8f9a0b1c"),
                            Code = "STRICT",
                            FixedFee = 5m,
                            IsActive = true,
                            Name = "Строгий",
                            PenaltyRate = 1.0m
                        },
                        new
                        {
                            Id = new Guid("7b8c9d0e-1f2a-43b4-5c6d-7e8f9a0b1c2d"),
                            Code = "SOFT",
                            FixedFee = 0m,
                            IsActive = true,
                            Name = "Мягкий",
                            PenaltyRate = 0.2m
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.Purpose", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Purposes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a1b2c3d-4e5f-46a7-8b9c-0d1e2f3a4b5c"),
                            Code = "PERSONAL",
                            IsActive = true,
                            Name = "Личные нужды"
                        },
                        new
                        {
                            Id = new Guid("1b2c3d4e-5f6a-47b8-9c0d-1e2f3a4b5c6d"),
                            Code = "BUSINESS",
                            IsActive = true,
                            Name = "Бизнес"
                        },
                        new
                        {
                            Id = new Guid("2c3d4e5f-6a7b-48c9-0d1e-2f3a4b5c6d7e"),
                            Code = "EDUCATION",
                            IsActive = true,
                            Name = "Образование"
                        },
                        new
                        {
                            Id = new Guid("3d4e5f6a-7b8c-49d0-1e2f-3a4b5c6d7e8f"),
                            Code = "MEDICAL",
                            IsActive = true,
                            Name = "Медицина"
                        },
                        new
                        {
                            Id = new Guid("4e5f6a7b-8c9d-40e1-2f3a-4b5c6d7e8f9a"),
                            Code = "OTHER",
                            IsActive = true,
                            Name = "Другое"
                        });
                });

            modelBuilder.Entity("MFO.Domain.Entities.RepaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("RepaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f2e1d0c-9b8a-47c6-b5a4-3f2e1d0c9b8a"),
                            Code = "CASH",
                            IsActive = true,
                            Name = "Наличные"
                        },
                        new
                        {
                            Id = new Guid("8a9b0c1d-2e3f-4a5b-8c9d-0e1f2a3b4c5d"),
                            Code = "CARD",
                            IsActive = true,
                            Name = "Карта"
                        },
                        new
                        {
                            Id = new Guid("4c5b6a7d-8e9f-40a1-b2c3-d4e5f6a7b8c9"),
                            Code = "BANK_TRANSFER",
                            IsActive = true,
                            Name = "Банковский перевод"
                        },
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-47e8-9f0a-1b2c3d4e5f6a"),
                            Code = "ONLINE",
                            IsActive = true,
                            Name = "Онлайн"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MFO.Domain.Entities.Customer", b =>
                {
                    b.HasOne("MFO.Domain.Entities.CustomerType", "CustomerType")
                        .WithMany("Customers")
                        .HasForeignKey("CustomerTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.CustomerStatus", "Status")
                        .WithMany("Customers")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MFO.Domain.Entities.Employee", b =>
                {
                    b.HasOne("MFO.Domain.Entities.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MFO.Domain.Entities.Loan", b =>
                {
                    b.HasOne("MFO.Domain.Entities.Branch", "Branch")
                        .WithMany("Loans")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.Employee", "Curator")
                        .WithMany("CuratedLoans")
                        .HasForeignKey("CuratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.Currency", "Currency")
                        .WithMany("Loans")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.Customer", "Customer")
                        .WithMany("Loans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.DisbursementMethod", "DisbursementMethod")
                        .WithMany("Loans")
                        .HasForeignKey("DisbursementMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.PaymentFrequency", "PaymentFrequency")
                        .WithMany("Loans")
                        .HasForeignKey("PaymentFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.PenaltyPolicy", "PenaltyPolicy")
                        .WithMany("Loans")
                        .HasForeignKey("PenaltyPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.LoanProduct", "Product")
                        .WithMany("Loans")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.Purpose", "Purpose")
                        .WithMany("Loans")
                        .HasForeignKey("PurposeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.RepaymentMethod", "RepaymentMethod")
                        .WithMany("Loans")
                        .HasForeignKey("RepaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.LoanStatus", "Status")
                        .WithMany("Loans")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Curator");

                    b.Navigation("Currency");

                    b.Navigation("Customer");

                    b.Navigation("DisbursementMethod");

                    b.Navigation("PaymentFrequency");

                    b.Navigation("PenaltyPolicy");

                    b.Navigation("Product");

                    b.Navigation("Purpose");

                    b.Navigation("RepaymentMethod");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanAccount", b =>
                {
                    b.HasOne("MFO.Domain.Entities.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanProduct", b =>
                {
                    b.HasOne("MFO.Domain.Entities.Currency", "Currency")
                        .WithMany("LoanProducts")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.PaymentFrequency", "PaymentFrequency")
                        .WithMany("LoanProducts")
                        .HasForeignKey("PaymentFrequencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.PenaltyPolicy", "PenaltyPolicy")
                        .WithMany("LoanProducts")
                        .HasForeignKey("PenaltyPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("PaymentFrequency");

                    b.Navigation("PenaltyPolicy");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanTransaction", b =>
                {
                    b.HasOne("MFO.Domain.Entities.LoanAccount", "LoanAccount")
                        .WithMany("Transactions")
                        .HasForeignKey("LoanAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.Loan", "Loan")
                        .WithMany()
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.LoanTransactionType", "TransactionType")
                        .WithMany("Transactions")
                        .HasForeignKey("TransactionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loan");

                    b.Navigation("LoanAccount");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MFO.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MFO.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MFO.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MFO.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MFO.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.Currency", b =>
                {
                    b.Navigation("LoanProducts");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.CustomerStatus", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("MFO.Domain.Entities.CustomerType", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("MFO.Domain.Entities.DisbursementMethod", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.Employee", b =>
                {
                    b.Navigation("CuratedLoans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanProduct", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanStatus", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.LoanTransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("MFO.Domain.Entities.PaymentFrequency", b =>
                {
                    b.Navigation("LoanProducts");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.PenaltyPolicy", b =>
                {
                    b.Navigation("LoanProducts");

                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.Purpose", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("MFO.Domain.Entities.RepaymentMethod", b =>
                {
                    b.Navigation("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
