namespace MFO.Application.Loans;

public sealed record CreateLoanRequest(
    string LoanNumber,
    Guid CustomerId,
    Guid ProductId,
    Guid StatusId,
    Guid CurrencyId,
    Guid BranchId,
    Guid CuratorId,
    Guid DisbursementMethodId,
    Guid RepaymentMethodId,
    Guid PurposeId,
    Guid PaymentFrequencyId,
    Guid PenaltyPolicyId,
    decimal PrincipalAmount,
    decimal InterestRate,
    decimal FeesAmount,
    decimal PenaltyRate,
    decimal TotalPayable,
    decimal OutstandingPrincipal,
    decimal OutstandingInterest,
    int TermMonths,
    DateOnly IssuedOn,
    DateOnly? ApprovedOn,
    DateOnly? DisbursedOn,
    DateOnly? MaturityOn,
    DateOnly? ClosedOn);
